name: unibill
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.4
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.7
  provider: ^5.0.0
  riverpod: ^1.0.0-dev.6
  reorderables: ^0.4.0
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0  
  qr_code_scanner: ^0.5.2
  sqflite: ^2.0.0 
  passkeys: ^0.1.0
  flutter_secure_storage: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```